server:
  port: 1110
  servlet:
    session:
      timeout: 60s
spring:
  application:
    name: master-server
  security:
    user:
      name: user
      password: 123456
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/master-server/
  server:
    rate-limiter-enabled: true
    eviction-interval-timer-in-ms: 60000